2022-03-15 15:43:09,581:INFO:PyCaret Supervised Module
2022-03-15 15:43:09,582:INFO:ML Usecase: classification
2022-03-15 15:43:09,582:INFO:version 2.3.6
2022-03-15 15:43:09,582:INFO:Initializing setup()
2022-03-15 15:43:09,582:INFO:setup(target=cancellation, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree', 'ks': 'KS Statistic Plot'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-03-15 15:43:09,582:INFO:Checking environment
2022-03-15 15:43:09,582:INFO:python_version: 3.8.6
2022-03-15 15:43:09,583:INFO:python_build: ('tags/v3.8.6:db45529', 'Sep 23 2020 15:52:53')
2022-03-15 15:43:09,583:INFO:machine: AMD64
2022-03-15 15:43:09,583:INFO:platform: Windows-10-10.0.19041-SP0
2022-03-15 15:43:09,592:INFO:Memory: svmem(total=17120387072, available=1359978496, percent=92.1, used=15760408576, free=1359978496)
2022-03-15 15:43:09,592:INFO:Physical Core: 4
2022-03-15 15:43:09,593:INFO:Logical Core: 4
2022-03-15 15:43:09,593:INFO:Checking libraries
2022-03-15 15:43:09,593:INFO:pd==1.4.1
2022-03-15 15:43:09,593:INFO:numpy==1.19.5
2022-03-15 15:43:09,593:INFO:sklearn==0.23.2
2022-03-15 15:43:09,593:INFO:lightgbm==3.3.2
2022-03-15 15:43:09,594:WARNING:catboost not found
2022-03-15 15:43:09,594:WARNING:xgboost not found
2022-03-15 15:43:10,694:INFO:mlflow==1.24.0
2022-03-15 15:43:10,694:INFO:Checking Exceptions
2022-03-15 15:43:10,694:INFO:Declaring global variables
2022-03-15 15:43:10,694:INFO:USI: 63e9
2022-03-15 15:43:10,694:INFO:pycaret_globals: {'gpu_param', 'fix_imbalance_param', '_available_plots', 'USI', 'target_param', 'n_jobs_param', 'log_plots_param', 'data_before_preprocess', 'fold_shuffle_param', 'fix_imbalance_method_param', '_all_models', 'experiment__', 'transform_target_method_param', '_all_metrics', 'imputation_regressor', '_internal_pipeline', '_gpu_n_jobs_param', 'pycaret_globals', 'fold_groups_param', 'X_test', 'prep_pipe', 'logging_param', '_all_models_internal', 'fold_generator', 'fold_param', 'y_train', 'exp_name_log', 'y_test', 'fold_groups_param_full', 'y', 'create_model_container', 'html_param', 'master_model_container', 'imputation_classifier', 'display_container', '_ml_usecase', 'X_train', 'seed', 'X', 'stratify_param', 'transform_target_param', 'iterative_imputation_iters_param'}
2022-03-15 15:43:10,695:INFO:Preparing display monitor
2022-03-15 15:43:10,695:INFO:Preparing display monitor
2022-03-15 15:43:10,710:INFO:Importing libraries
2022-03-15 15:43:10,710:INFO:Copying data for preprocessing
2022-03-15 15:43:10,737:INFO:Declaring preprocessing parameters
2022-03-15 15:43:10,749:INFO:Creating preprocessing pipeline
2022-03-15 15:43:10,940:INFO:Preprocessing pipeline created successfully
2022-03-15 15:43:10,941:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-03-15 15:43:10,941:INFO:Creating global containers
2022-03-15 15:43:11,041:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-03-15 15:43:24,190:WARNING:Couldn't import xgboost.XGBClassifier
2022-03-15 15:43:24,191:WARNING:Couldn't import catboost.CatBoostClassifier
2022-03-15 15:43:24,278:WARNING:Couldn't import xgboost.XGBClassifier
2022-03-15 15:43:24,279:WARNING:Couldn't import catboost.CatBoostClassifier
2022-03-15 15:43:24,282:INFO:Creating grid variables
2022-03-15 15:43:24,326:INFO:create_model_container: 0
2022-03-15 15:43:24,326:INFO:master_model_container: 0
2022-03-15 15:43:24,326:INFO:display_container: 1
2022-03-15 15:43:24,331:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=[],
                                      target='cancellation',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='cancellation')),
                ('fix_perfect', Remove_100(target='cancellation')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2022-03-15 15:43:24,331:INFO:setup() succesfully completed......................................
2022-03-15 15:45:31,890:INFO:Initializing compare_models()
2022-03-15 15:45:31,890:INFO:compare_models(include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, probability_threshold=None, verbose=True, display=None, exclude=None)
2022-03-15 15:45:31,890:INFO:Checking exceptions
2022-03-15 15:45:31,892:INFO:Preparing display monitor
2022-03-15 15:45:31,893:INFO:Preparing display monitor
2022-03-15 15:45:31,921:INFO:Initializing Logistic Regression
2022-03-15 15:45:31,921:INFO:Total runtime is 0.0 minutes
2022-03-15 15:45:31,929:INFO:SubProcess create_model() called ==================================
2022-03-15 15:45:31,930:INFO:Initializing create_model()
2022-03-15 15:45:31,930:INFO:create_model(estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:45:31,930:INFO:Checking exceptions
2022-03-15 15:45:31,930:INFO:Importing libraries
2022-03-15 15:45:31,930:INFO:Copying training dataset
2022-03-15 15:45:31,941:INFO:Defining folds
2022-03-15 15:45:31,941:INFO:Declaring metric variables
2022-03-15 15:45:31,951:INFO:Importing untrained model
2022-03-15 15:45:31,961:INFO:Logistic Regression Imported succesfully
2022-03-15 15:45:31,979:INFO:Starting cross validation
2022-03-15 15:45:31,979:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:46:16,743:INFO:Calculating mean and std
2022-03-15 15:46:16,744:INFO:Creating metrics dataframe
2022-03-15 15:46:17,378:INFO:Uploading results into container
2022-03-15 15:46:17,381:INFO:Uploading model into container now
2022-03-15 15:46:17,381:INFO:create_model_container: 1
2022-03-15 15:46:17,381:INFO:master_model_container: 1
2022-03-15 15:46:17,381:INFO:display_container: 2
2022-03-15 15:46:17,381:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=857, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2022-03-15 15:46:17,381:INFO:create_model() succesfully completed......................................
2022-03-15 15:46:17,554:INFO:SubProcess create_model() end ==================================
2022-03-15 15:46:17,555:INFO:Creating metrics dataframe
2022-03-15 15:46:17,610:INFO:Initializing K Neighbors Classifier
2022-03-15 15:46:17,611:INFO:Total runtime is 0.7614993651707967 minutes
2022-03-15 15:46:17,621:INFO:SubProcess create_model() called ==================================
2022-03-15 15:46:17,621:INFO:Initializing create_model()
2022-03-15 15:46:17,621:INFO:create_model(estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:46:17,622:INFO:Checking exceptions
2022-03-15 15:46:17,622:INFO:Importing libraries
2022-03-15 15:46:17,622:INFO:Copying training dataset
2022-03-15 15:46:17,631:INFO:Defining folds
2022-03-15 15:46:17,632:INFO:Declaring metric variables
2022-03-15 15:46:17,642:INFO:Importing untrained model
2022-03-15 15:46:17,650:INFO:K Neighbors Classifier Imported succesfully
2022-03-15 15:46:17,667:INFO:Starting cross validation
2022-03-15 15:46:17,667:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:51:07,136:WARNING:create_model() for knn raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:51:07,899:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\cassi\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 434, in result
    self._condition.wait(timeout)
  File "C:\Users\cassi\AppData\Local\Programs\Python\Python38\lib\threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

2022-03-15 15:51:07,899:INFO:Initializing create_model()
2022-03-15 15:51:07,900:INFO:create_model(estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:51:07,900:INFO:Checking exceptions
2022-03-15 15:51:07,900:INFO:Importing libraries
2022-03-15 15:51:07,900:INFO:Copying training dataset
2022-03-15 15:51:07,914:INFO:Defining folds
2022-03-15 15:51:07,915:INFO:Declaring metric variables
2022-03-15 15:51:07,925:INFO:Importing untrained model
2022-03-15 15:51:07,934:INFO:K Neighbors Classifier Imported succesfully
2022-03-15 15:51:07,950:INFO:Starting cross validation
2022-03-15 15:51:07,951:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,005:ERROR:create_model() for knn raised an exception or returned all 0.0:
2022-03-15 15:53:06,097:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\cassi\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 434, in result
    self._condition.wait(timeout)
  File "C:\Users\cassi\AppData\Local\Programs\Python\Python38\lib\threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\cassi\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 434, in result
    self._condition.wait(timeout)
  File "C:\Users\cassi\AppData\Local\Programs\Python\Python38\lib\threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 955, in retrieve
    backend.abort_everything(ensure_ready=ensure_ready)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 561, in abort_everything
    self._workers.terminate(kill_workers=True)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 86, in terminate
    self._temp_folder_manager._unregister_temporary_resources()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 635, in _unregister_temporary_resources
    self._unregister_temporary_resources(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 640, in _unregister_temporary_resources
    resource_tracker.unregister(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 195, in unregister
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 1064, in __call__
    self._terminate_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 757, in _terminate_backend
    self._backend.terminate()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 551, in terminate
    self._workers._temp_folder_manager._unlink_temporary_resources(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 624, in _unlink_temporary_resources
    resource_tracker.maybe_unlink(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 200, in maybe_unlink
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,099:INFO:Initializing Naive Bayes
2022-03-15 15:53:06,100:INFO:Total runtime is 7.5696427861849465 minutes
2022-03-15 15:53:06,108:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:06,109:INFO:Initializing create_model()
2022-03-15 15:53:06,109:INFO:create_model(estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,109:INFO:Checking exceptions
2022-03-15 15:53:06,109:INFO:Importing libraries
2022-03-15 15:53:06,109:INFO:Copying training dataset
2022-03-15 15:53:06,117:INFO:Defining folds
2022-03-15 15:53:06,118:INFO:Declaring metric variables
2022-03-15 15:53:06,125:INFO:Importing untrained model
2022-03-15 15:53:06,132:INFO:Naive Bayes Imported succesfully
2022-03-15 15:53:06,149:INFO:Starting cross validation
2022-03-15 15:53:06,149:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,150:WARNING:create_model() for nb raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:06,151:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,151:INFO:Initializing create_model()
2022-03-15 15:53:06,151:INFO:create_model(estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,151:INFO:Checking exceptions
2022-03-15 15:53:06,151:INFO:Importing libraries
2022-03-15 15:53:06,151:INFO:Copying training dataset
2022-03-15 15:53:06,160:INFO:Defining folds
2022-03-15 15:53:06,160:INFO:Declaring metric variables
2022-03-15 15:53:06,166:INFO:Importing untrained model
2022-03-15 15:53:06,173:INFO:Naive Bayes Imported succesfully
2022-03-15 15:53:06,188:INFO:Starting cross validation
2022-03-15 15:53:06,189:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,190:ERROR:create_model() for nb raised an exception or returned all 0.0:
2022-03-15 15:53:06,191:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,195:INFO:Initializing Decision Tree Classifier
2022-03-15 15:53:06,195:INFO:Total runtime is 7.571226112047831 minutes
2022-03-15 15:53:06,202:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:06,203:INFO:Initializing create_model()
2022-03-15 15:53:06,203:INFO:create_model(estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,203:INFO:Checking exceptions
2022-03-15 15:53:06,203:INFO:Importing libraries
2022-03-15 15:53:06,203:INFO:Copying training dataset
2022-03-15 15:53:06,211:INFO:Defining folds
2022-03-15 15:53:06,211:INFO:Declaring metric variables
2022-03-15 15:53:06,219:INFO:Importing untrained model
2022-03-15 15:53:06,226:INFO:Decision Tree Classifier Imported succesfully
2022-03-15 15:53:06,242:INFO:Starting cross validation
2022-03-15 15:53:06,243:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,246:WARNING:create_model() for dt raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:06,247:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,247:INFO:Initializing create_model()
2022-03-15 15:53:06,247:INFO:create_model(estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,247:INFO:Checking exceptions
2022-03-15 15:53:06,247:INFO:Importing libraries
2022-03-15 15:53:06,247:INFO:Copying training dataset
2022-03-15 15:53:06,260:INFO:Defining folds
2022-03-15 15:53:06,260:INFO:Declaring metric variables
2022-03-15 15:53:06,272:INFO:Importing untrained model
2022-03-15 15:53:06,279:INFO:Decision Tree Classifier Imported succesfully
2022-03-15 15:53:06,294:INFO:Starting cross validation
2022-03-15 15:53:06,295:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,296:ERROR:create_model() for dt raised an exception or returned all 0.0:
2022-03-15 15:53:06,297:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,302:INFO:Initializing SVM - Linear Kernel
2022-03-15 15:53:06,302:INFO:Total runtime is 7.573009471098581 minutes
2022-03-15 15:53:06,310:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:06,310:INFO:Initializing create_model()
2022-03-15 15:53:06,311:INFO:create_model(estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,311:INFO:Checking exceptions
2022-03-15 15:53:06,311:INFO:Importing libraries
2022-03-15 15:53:06,311:INFO:Copying training dataset
2022-03-15 15:53:06,319:INFO:Defining folds
2022-03-15 15:53:06,319:INFO:Declaring metric variables
2022-03-15 15:53:06,327:INFO:Importing untrained model
2022-03-15 15:53:06,334:INFO:SVM - Linear Kernel Imported succesfully
2022-03-15 15:53:06,350:INFO:Starting cross validation
2022-03-15 15:53:06,350:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,351:WARNING:create_model() for svm raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:06,352:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,352:INFO:Initializing create_model()
2022-03-15 15:53:06,352:INFO:create_model(estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,352:INFO:Checking exceptions
2022-03-15 15:53:06,353:INFO:Importing libraries
2022-03-15 15:53:06,353:INFO:Copying training dataset
2022-03-15 15:53:06,360:INFO:Defining folds
2022-03-15 15:53:06,361:INFO:Declaring metric variables
2022-03-15 15:53:06,368:INFO:Importing untrained model
2022-03-15 15:53:06,377:INFO:SVM - Linear Kernel Imported succesfully
2022-03-15 15:53:06,393:INFO:Starting cross validation
2022-03-15 15:53:06,394:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,395:ERROR:create_model() for svm raised an exception or returned all 0.0:
2022-03-15 15:53:06,396:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,400:INFO:Initializing Ridge Classifier
2022-03-15 15:53:06,400:INFO:Total runtime is 7.574642797311147 minutes
2022-03-15 15:53:06,408:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:06,408:INFO:Initializing create_model()
2022-03-15 15:53:06,410:INFO:create_model(estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,410:INFO:Checking exceptions
2022-03-15 15:53:06,410:INFO:Importing libraries
2022-03-15 15:53:06,410:INFO:Copying training dataset
2022-03-15 15:53:06,417:INFO:Defining folds
2022-03-15 15:53:06,419:INFO:Declaring metric variables
2022-03-15 15:53:06,427:INFO:Importing untrained model
2022-03-15 15:53:06,435:INFO:Ridge Classifier Imported succesfully
2022-03-15 15:53:06,450:INFO:Starting cross validation
2022-03-15 15:53:06,451:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,452:WARNING:create_model() for ridge raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:06,453:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,453:INFO:Initializing create_model()
2022-03-15 15:53:06,454:INFO:create_model(estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,454:INFO:Checking exceptions
2022-03-15 15:53:06,454:INFO:Importing libraries
2022-03-15 15:53:06,454:INFO:Copying training dataset
2022-03-15 15:53:06,462:INFO:Defining folds
2022-03-15 15:53:06,462:INFO:Declaring metric variables
2022-03-15 15:53:06,469:INFO:Importing untrained model
2022-03-15 15:53:06,479:INFO:Ridge Classifier Imported succesfully
2022-03-15 15:53:06,496:INFO:Starting cross validation
2022-03-15 15:53:06,496:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,497:ERROR:create_model() for ridge raised an exception or returned all 0.0:
2022-03-15 15:53:06,498:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,502:INFO:Initializing Random Forest Classifier
2022-03-15 15:53:06,503:INFO:Total runtime is 7.576359442869822 minutes
2022-03-15 15:53:06,511:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:06,512:INFO:Initializing create_model()
2022-03-15 15:53:06,512:INFO:create_model(estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,512:INFO:Checking exceptions
2022-03-15 15:53:06,512:INFO:Importing libraries
2022-03-15 15:53:06,512:INFO:Copying training dataset
2022-03-15 15:53:06,519:INFO:Defining folds
2022-03-15 15:53:06,520:INFO:Declaring metric variables
2022-03-15 15:53:06,527:INFO:Importing untrained model
2022-03-15 15:53:06,535:INFO:Random Forest Classifier Imported succesfully
2022-03-15 15:53:06,550:INFO:Starting cross validation
2022-03-15 15:53:06,550:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,551:WARNING:create_model() for rf raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:06,552:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,552:INFO:Initializing create_model()
2022-03-15 15:53:06,552:INFO:create_model(estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,552:INFO:Checking exceptions
2022-03-15 15:53:06,553:INFO:Importing libraries
2022-03-15 15:53:06,553:INFO:Copying training dataset
2022-03-15 15:53:06,561:INFO:Defining folds
2022-03-15 15:53:06,561:INFO:Declaring metric variables
2022-03-15 15:53:06,567:INFO:Importing untrained model
2022-03-15 15:53:06,575:INFO:Random Forest Classifier Imported succesfully
2022-03-15 15:53:06,593:INFO:Starting cross validation
2022-03-15 15:53:06,594:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,595:ERROR:create_model() for rf raised an exception or returned all 0.0:
2022-03-15 15:53:06,597:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,601:INFO:Initializing Quadratic Discriminant Analysis
2022-03-15 15:53:06,601:INFO:Total runtime is 7.577992777029673 minutes
2022-03-15 15:53:06,608:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:06,609:INFO:Initializing create_model()
2022-03-15 15:53:06,609:INFO:create_model(estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,609:INFO:Checking exceptions
2022-03-15 15:53:06,609:INFO:Importing libraries
2022-03-15 15:53:06,609:INFO:Copying training dataset
2022-03-15 15:53:06,617:INFO:Defining folds
2022-03-15 15:53:06,617:INFO:Declaring metric variables
2022-03-15 15:53:06,626:INFO:Importing untrained model
2022-03-15 15:53:06,634:INFO:Quadratic Discriminant Analysis Imported succesfully
2022-03-15 15:53:06,651:INFO:Starting cross validation
2022-03-15 15:53:06,652:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,653:WARNING:create_model() for qda raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:06,654:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,654:INFO:Initializing create_model()
2022-03-15 15:53:06,654:INFO:create_model(estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,654:INFO:Checking exceptions
2022-03-15 15:53:06,654:INFO:Importing libraries
2022-03-15 15:53:06,654:INFO:Copying training dataset
2022-03-15 15:53:06,662:INFO:Defining folds
2022-03-15 15:53:06,662:INFO:Declaring metric variables
2022-03-15 15:53:06,669:INFO:Importing untrained model
2022-03-15 15:53:06,679:INFO:Quadratic Discriminant Analysis Imported succesfully
2022-03-15 15:53:06,696:INFO:Starting cross validation
2022-03-15 15:53:06,697:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,698:ERROR:create_model() for qda raised an exception or returned all 0.0:
2022-03-15 15:53:06,699:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,703:INFO:Initializing Ada Boost Classifier
2022-03-15 15:53:06,703:INFO:Total runtime is 7.57969278494517 minutes
2022-03-15 15:53:06,711:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:06,712:INFO:Initializing create_model()
2022-03-15 15:53:06,712:INFO:create_model(estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,712:INFO:Checking exceptions
2022-03-15 15:53:06,712:INFO:Importing libraries
2022-03-15 15:53:06,712:INFO:Copying training dataset
2022-03-15 15:53:06,720:INFO:Defining folds
2022-03-15 15:53:06,720:INFO:Declaring metric variables
2022-03-15 15:53:06,728:INFO:Importing untrained model
2022-03-15 15:53:06,736:INFO:Ada Boost Classifier Imported succesfully
2022-03-15 15:53:06,750:INFO:Starting cross validation
2022-03-15 15:53:06,751:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,752:WARNING:create_model() for ada raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:06,753:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,753:INFO:Initializing create_model()
2022-03-15 15:53:06,753:INFO:create_model(estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,753:INFO:Checking exceptions
2022-03-15 15:53:06,753:INFO:Importing libraries
2022-03-15 15:53:06,753:INFO:Copying training dataset
2022-03-15 15:53:06,761:INFO:Defining folds
2022-03-15 15:53:06,761:INFO:Declaring metric variables
2022-03-15 15:53:06,769:INFO:Importing untrained model
2022-03-15 15:53:06,777:INFO:Ada Boost Classifier Imported succesfully
2022-03-15 15:53:06,794:INFO:Starting cross validation
2022-03-15 15:53:06,794:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,795:ERROR:create_model() for ada raised an exception or returned all 0.0:
2022-03-15 15:53:06,796:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,801:INFO:Initializing Gradient Boosting Classifier
2022-03-15 15:53:06,801:INFO:Total runtime is 7.581326127052307 minutes
2022-03-15 15:53:06,808:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:06,809:INFO:Initializing create_model()
2022-03-15 15:53:06,809:INFO:create_model(estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,809:INFO:Checking exceptions
2022-03-15 15:53:06,809:INFO:Importing libraries
2022-03-15 15:53:06,809:INFO:Copying training dataset
2022-03-15 15:53:06,819:INFO:Defining folds
2022-03-15 15:53:06,819:INFO:Declaring metric variables
2022-03-15 15:53:06,827:INFO:Importing untrained model
2022-03-15 15:53:06,836:INFO:Gradient Boosting Classifier Imported succesfully
2022-03-15 15:53:06,854:INFO:Starting cross validation
2022-03-15 15:53:06,855:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,856:WARNING:create_model() for gbc raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:06,856:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,857:INFO:Initializing create_model()
2022-03-15 15:53:06,857:INFO:create_model(estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,857:INFO:Checking exceptions
2022-03-15 15:53:06,857:INFO:Importing libraries
2022-03-15 15:53:06,857:INFO:Copying training dataset
2022-03-15 15:53:06,865:INFO:Defining folds
2022-03-15 15:53:06,866:INFO:Declaring metric variables
2022-03-15 15:53:06,878:INFO:Importing untrained model
2022-03-15 15:53:06,886:INFO:Gradient Boosting Classifier Imported succesfully
2022-03-15 15:53:06,904:INFO:Starting cross validation
2022-03-15 15:53:06,905:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,906:ERROR:create_model() for gbc raised an exception or returned all 0.0:
2022-03-15 15:53:06,907:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,912:INFO:Initializing Linear Discriminant Analysis
2022-03-15 15:53:06,912:INFO:Total runtime is 7.5831761399904885 minutes
2022-03-15 15:53:06,925:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:06,926:INFO:Initializing create_model()
2022-03-15 15:53:06,926:INFO:create_model(estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,926:INFO:Checking exceptions
2022-03-15 15:53:06,926:INFO:Importing libraries
2022-03-15 15:53:06,926:INFO:Copying training dataset
2022-03-15 15:53:06,934:INFO:Defining folds
2022-03-15 15:53:06,934:INFO:Declaring metric variables
2022-03-15 15:53:06,943:INFO:Importing untrained model
2022-03-15 15:53:06,950:INFO:Linear Discriminant Analysis Imported succesfully
2022-03-15 15:53:06,966:INFO:Starting cross validation
2022-03-15 15:53:06,967:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:06,968:WARNING:create_model() for lda raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:06,968:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:06,969:INFO:Initializing create_model()
2022-03-15 15:53:06,969:INFO:create_model(estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:06,969:INFO:Checking exceptions
2022-03-15 15:53:06,969:INFO:Importing libraries
2022-03-15 15:53:06,969:INFO:Copying training dataset
2022-03-15 15:53:06,978:INFO:Defining folds
2022-03-15 15:53:06,978:INFO:Declaring metric variables
2022-03-15 15:53:06,986:INFO:Importing untrained model
2022-03-15 15:53:06,995:INFO:Linear Discriminant Analysis Imported succesfully
2022-03-15 15:53:07,013:INFO:Starting cross validation
2022-03-15 15:53:07,014:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:07,015:ERROR:create_model() for lda raised an exception or returned all 0.0:
2022-03-15 15:53:07,016:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:07,020:INFO:Initializing Extra Trees Classifier
2022-03-15 15:53:07,021:INFO:Total runtime is 7.584992802143097 minutes
2022-03-15 15:53:07,030:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:07,031:INFO:Initializing create_model()
2022-03-15 15:53:07,031:INFO:create_model(estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:07,031:INFO:Checking exceptions
2022-03-15 15:53:07,031:INFO:Importing libraries
2022-03-15 15:53:07,031:INFO:Copying training dataset
2022-03-15 15:53:07,039:INFO:Defining folds
2022-03-15 15:53:07,039:INFO:Declaring metric variables
2022-03-15 15:53:07,047:INFO:Importing untrained model
2022-03-15 15:53:07,056:INFO:Extra Trees Classifier Imported succesfully
2022-03-15 15:53:07,073:INFO:Starting cross validation
2022-03-15 15:53:07,074:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:07,076:WARNING:create_model() for et raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:07,077:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:07,077:INFO:Initializing create_model()
2022-03-15 15:53:07,078:INFO:create_model(estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:07,078:INFO:Checking exceptions
2022-03-15 15:53:07,078:INFO:Importing libraries
2022-03-15 15:53:07,078:INFO:Copying training dataset
2022-03-15 15:53:07,086:INFO:Defining folds
2022-03-15 15:53:07,086:INFO:Declaring metric variables
2022-03-15 15:53:07,096:INFO:Importing untrained model
2022-03-15 15:53:07,103:INFO:Extra Trees Classifier Imported succesfully
2022-03-15 15:53:07,120:INFO:Starting cross validation
2022-03-15 15:53:07,121:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:07,122:ERROR:create_model() for et raised an exception or returned all 0.0:
2022-03-15 15:53:07,123:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:07,127:INFO:Initializing Light Gradient Boosting Machine
2022-03-15 15:53:07,128:INFO:Total runtime is 7.586776121457418 minutes
2022-03-15 15:53:07,137:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:07,138:INFO:Initializing create_model()
2022-03-15 15:53:07,138:INFO:create_model(estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:07,138:INFO:Checking exceptions
2022-03-15 15:53:07,138:INFO:Importing libraries
2022-03-15 15:53:07,138:INFO:Copying training dataset
2022-03-15 15:53:07,147:INFO:Defining folds
2022-03-15 15:53:07,148:INFO:Declaring metric variables
2022-03-15 15:53:07,155:INFO:Importing untrained model
2022-03-15 15:53:07,165:INFO:Light Gradient Boosting Machine Imported succesfully
2022-03-15 15:53:07,181:INFO:Starting cross validation
2022-03-15 15:53:07,182:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:07,183:WARNING:create_model() for lightgbm raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:07,184:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:07,184:INFO:Initializing create_model()
2022-03-15 15:53:07,184:INFO:create_model(estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:07,184:INFO:Checking exceptions
2022-03-15 15:53:07,184:INFO:Importing libraries
2022-03-15 15:53:07,184:INFO:Copying training dataset
2022-03-15 15:53:07,192:INFO:Defining folds
2022-03-15 15:53:07,192:INFO:Declaring metric variables
2022-03-15 15:53:07,200:INFO:Importing untrained model
2022-03-15 15:53:07,208:INFO:Light Gradient Boosting Machine Imported succesfully
2022-03-15 15:53:07,222:INFO:Starting cross validation
2022-03-15 15:53:07,223:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:07,224:ERROR:create_model() for lightgbm raised an exception or returned all 0.0:
2022-03-15 15:53:07,225:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:07,229:INFO:Initializing Dummy Classifier
2022-03-15 15:53:07,229:INFO:Total runtime is 7.588459451993306 minutes
2022-03-15 15:53:07,237:INFO:SubProcess create_model() called ==================================
2022-03-15 15:53:07,237:INFO:Initializing create_model()
2022-03-15 15:53:07,237:INFO:create_model(estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:07,237:INFO:Checking exceptions
2022-03-15 15:53:07,238:INFO:Importing libraries
2022-03-15 15:53:07,238:INFO:Copying training dataset
2022-03-15 15:53:07,246:INFO:Defining folds
2022-03-15 15:53:07,246:INFO:Declaring metric variables
2022-03-15 15:53:07,252:INFO:Importing untrained model
2022-03-15 15:53:07,259:INFO:Dummy Classifier Imported succesfully
2022-03-15 15:53:07,275:INFO:Starting cross validation
2022-03-15 15:53:07,276:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:07,276:WARNING:create_model() for dummy raised an exception or returned all 0.0, trying without fit_kwargs:
2022-03-15 15:53:07,277:WARNING:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:07,277:INFO:Initializing create_model()
2022-03-15 15:53:07,277:INFO:create_model(estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x0000026990196970>, kwargs={})
2022-03-15 15:53:07,277:INFO:Checking exceptions
2022-03-15 15:53:07,277:INFO:Importing libraries
2022-03-15 15:53:07,277:INFO:Copying training dataset
2022-03-15 15:53:07,285:INFO:Defining folds
2022-03-15 15:53:07,286:INFO:Declaring metric variables
2022-03-15 15:53:07,293:INFO:Importing untrained model
2022-03-15 15:53:07,300:INFO:Dummy Classifier Imported succesfully
2022-03-15 15:53:07,315:INFO:Starting cross validation
2022-03-15 15:53:07,316:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-03-15 15:53:07,317:ERROR:create_model() for dummy raised an exception or returned all 0.0:
2022-03-15 15:53:07,318:ERROR:Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_parallel_backends.py", line 494, in configure
    self._workers = get_memmapping_executor(
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 531, in __init__
    self.set_current_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in set_current_context
    self.register_new_context(context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 560, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\_memmapping_reducer.py", line 590, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 190, in register
    self.ensure_running()
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 102, in ensure_running
    if self._check_alive():
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 182, in _check_alive
    self._send('PROBE', '', '')
  File "c:\users\cassi\desktop\cassio\01 - pessoal\no_show_project\venv\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 209, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument

2022-03-15 15:53:07,341:INFO:Initializing create_model()
2022-03-15 15:53:07,341:INFO:create_model(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=857, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=None, kwargs={})
2022-03-15 15:53:07,341:INFO:Checking exceptions
2022-03-15 15:53:07,342:INFO:Importing libraries
2022-03-15 15:53:07,342:INFO:Copying training dataset
2022-03-15 15:53:07,349:INFO:Defining folds
2022-03-15 15:53:07,349:INFO:Declaring metric variables
2022-03-15 15:53:07,349:INFO:Importing untrained model
2022-03-15 15:53:07,349:INFO:Declaring custom model
2022-03-15 15:53:07,349:INFO:Logistic Regression Imported succesfully
2022-03-15 15:53:07,350:INFO:Cross validation set to False
2022-03-15 15:53:07,350:INFO:Fitting Model
